### ISSUE TITLE
Feature request: Allow memo field to be set for BTC -> ETH transactions and provide it as payload data

### ISSUE THREAD

**Issue by javgh** [wildbunny/metaexchange#16]
I noticed that for ETH -> BTC transactions the exchange expects to see 'deposit data' with the incoming Ethereum transaction to be able to correctly credit it.

It would be create if something like this would exist for the reverse direction as well. That is, if I'm calling the API to prepare an exchange from BTC to ETH, I would like to be able to specify a small amount of data which will be sent alongside the ether to the destination address when the exchange happens. (Or alternatively the API could return a unique identifier, that will be used, if you don't want to deal with user-supplied data.)

That would make it much easier to track multiple exchanges. Another way would be of course to create multiple Ethereum accounts to be able to tell things apart, but from what I gather, that's not really a recommended approach and would also not work for contracts, which only have a single address.

**Comment by wildbunny** [comment]
This is tough to implement neatly in the existing code base. A workaround is to use a new ETH receiving address for each customer.
